version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:13
    container_name: cv-data-storage-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cv_data_storage
      POSTGRES_USER: cv_admin
      POSTGRES_PASSWORD: cv_admin

networks:
  default:
    driver: bridge

volumes:
  pgdata:
